title: ILiADS Static Demo Site
author:
  name: GitHub User
  email: your-email@domain.com
description: >
 Hi, I'm Emily. I am testing out using Jekyll for making a static site on GitHub.

minima:
  date_format: "%b %-d, %Y"
  social_links:
    - { icon: "github", title: "Minima Theme repository at GitHub", url: "https://github.com/jekyll/minima" }
    - { icon: "x-twitter", title: "Jekyll profile at X (formerly Twitter)", url: "https://x.com/jekyllrb" }
  show_excerpts: true
  skin: solarized-dark # Options: auto, classic, dark, solarized, solarized-light, solarized-dark

# Build settings
baseurl: /ILiADS-Static-Demo
remote_theme: jekyll/minima
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-seo-tag

sass:
  quiet_deps: true
  silence_deprecations: [import]
